id = "baiteryamato.dynamic_movement_remake"
name = "Movimentação Dinâmica Remake"
version = "0.2.3"
api = ">=0.5.0 <0.6.0"
entrypoint = "main.lua"
games = ["oot"]

[provider]
abi_version = "1.0"
win64 = "provider/dynamic_movement_remake.dll"
